name: 커밋 감지하고 자동으로 업데이트하기

on:
  push:
    branch:
      - main


jobs:
  CI-CD-TEST:
    runs-on: ubuntu-22.04

    steps:
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.LINUX_KEY }}" > ~/.ssh/yoo
          sudo chmod 600 ~/.ssh/yoo

      - name: Add EC2 host to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.AWS_IP }} >> ~/.ssh/known_hosts

      - name: EC2 접속하기
        run: |
          ssh -i ~/.ssh/yoo ubuntu@${{ secrets.AWS_IP }} << 'EOF'
            cd /home/ubuntu/spring/Spring-Boot/study
            echo "이동 완료"
          
            git pull origin
            echo "git pull 완료"
          
            ./gradlew clean build
            echo "빌드 완료"
          
            cd ./build/libs
            echo "jar 파일 위치로 이동"
          
            pkill -f 'java -jar' || true
          
            sudo java -jar study*SNAPSHOT.jar &
            echo "jar 파일 실행"
          EOF
